name: CMake

on:
  workflow_dispatch:
  push:

env:
  BUILD_TYPE: Release

jobs:
  build:
    # See: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 7
    strategy:
      fail-fast: false
      matrix:
        config:
        - { build_type: "Release", cc: "gcc-9", cxx: "g++-9" }
        - { build_type: "Release", cc: "clang-10", cxx: "clang++-10" }

    steps:
    - uses: actions/checkout@v2

    - name: Update apt
      run: sudo apt-get update

    - name: Install Dependencies
      run: sudo apt-get install xorg-dev libgl1-mesa-dev clang-10 libc++-10-dev libsdl2-dev

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: CC=${{matrix.config.cc}} CXX=${{matrix.config.cxx}} cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DUSE_LIBCXX=ON

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE -j 4

#    - name: Package
#      working-directory: ${{runner.workspace}}/build
#      shell: bash
#      run: cpack .

#    - name: Upload Artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: package-${{matrix.config.cc}}
#        if-no-files-found: error
#        path: ${{runner.workspace}}/build/Weep-0.0.1-Linux.7z